// Store data for Stargas locations across Ireland
const storeData = [
    {
        id: '1',
        name: 'Stargas Dublin City',
        address: '123 O\'Connell Street',
        city: 'Dublin',
        county: 'Dublin',
        eircode: 'D01 ABC1',
        coordinates: { lat: 53.3498, lng: -6.2603 },
        phone: '+353 1 234 5678',
        email: 'dublin.city@stargas.ie',
        openingHours: {
            monday: '24 Hours',
            tuesday: '24 Hours',
            wednesday: '24 Hours',
            thursday: '24 Hours',
            friday: '24 Hours',
            saturday: '24 Hours',
            sunday: '24 Hours'
        },
        services: ['fuel', 'shop', 'car-wash', 'coffee', 'atm'],
        amenities: ['Free WiFi', 'Parking', 'Disabled Access', 'Toilets'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded', 'AdBlue'],
        manager: 'John O\'Sullivan',
        established: 2018,
        is24Hours: true,
        hasCarWash: true,
        hasShop: true,
        hasCafe: true,
        hasATM: true,
    },
    {
        id: '2',
        name: 'Stargas Cork Central',
        address: '456 Patrick Street',
        city: 'Cork',
        county: 'Cork',
        eircode: 'T12 XYZ2',
        coordinates: { lat: 51.8985, lng: -8.4756 },
        phone: '+353 21 234 5678',
        email: 'cork.central@stargas.ie',
        openingHours: {
            monday: '6:00 AM - 11:00 PM',
            tuesday: '6:00 AM - 11:00 PM',
            wednesday: '6:00 AM - 11:00 PM',
            thursday: '6:00 AM - 11:00 PM',
            friday: '6:00 AM - 12:00 AM',
            saturday: '7:00 AM - 12:00 AM',
            sunday: '8:00 AM - 10:00 PM'
        },
        services: ['fuel', 'shop', 'coffee', 'atm'],
        amenities: ['Free WiFi', 'Parking', 'Disabled Access'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded'],
        manager: 'Mary Murphy',
        established: 2015,
        is24Hours: false,
        hasCarWash: false,
        hasShop: true,
        hasCafe: true,
        hasATM: true,
    },
    {
        id: '3',
        name: 'Stargas Galway Bay',
        address: '789 Shop Street',
        city: 'Galway',
        county: 'Galway',
        eircode: 'H91 DEF3',
        coordinates: { lat: 53.2707, lng: -9.0568 },
        phone: '+353 91 234 5678',
        email: 'galway.bay@stargas.ie',
        openingHours: {
            monday: '24 Hours',
            tuesday: '24 Hours',
            wednesday: '24 Hours',
            thursday: '24 Hours',
            friday: '24 Hours',
            saturday: '24 Hours',
            sunday: '24 Hours'
        },
        services: ['fuel', 'shop', 'car-wash'],
        amenities: ['Parking', 'Disabled Access', 'Toilets'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded', 'AdBlue'],
        manager: 'Seán Kelly',
        established: 2020,
        is24Hours: true,
        hasCarWash: true,
        hasShop: true,
        hasCafe: false,
        hasATM: false,
    },
    {
        id: '4',
        name: 'Stargas Limerick Junction',
        address: '321 William Street',
        city: 'Limerick',
        county: 'Limerick',
        eircode: 'V94 GHI4',
        coordinates: { lat: 52.6638, lng: -8.6267 },
        phone: '+353 61 234 5678',
        email: 'limerick.junction@stargas.ie',
        openingHours: {
            monday: '5:00 AM - 11:00 PM',
            tuesday: '5:00 AM - 11:00 PM',
            wednesday: '5:00 AM - 11:00 PM',
            thursday: '5:00 AM - 11:00 PM',
            friday: '5:00 AM - 12:00 AM',
            saturday: '6:00 AM - 12:00 AM',
            sunday: '7:00 AM - 10:00 PM'
        },
        services: ['fuel', 'shop', 'coffee', 'car-wash', 'atm'],
        amenities: ['Free WiFi', 'Parking', 'Disabled Access', 'Toilets', 'Electric Charging'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded', 'AdBlue', 'Electric'],
        manager: 'Emma Walsh',
        established: 2019,
        is24Hours: false,
        hasCarWash: true,
        hasShop: true,
        hasCafe: true,
        hasATM: true,
    },
    {
        id: '5',
        name: 'Stargas Waterford Quay',
        address: '654 The Quay',
        city: 'Waterford',
        county: 'Waterford',
        eircode: 'X91 JKL5',
        coordinates: { lat: 52.2593, lng: -7.1101 },
        phone: '+353 51 234 5678',
        email: 'waterford.quay@stargas.ie',
        openingHours: {
            monday: '6:00 AM - 10:00 PM',
            tuesday: '6:00 AM - 10:00 PM',
            wednesday: '6:00 AM - 10:00 PM',
            thursday: '6:00 AM - 10:00 PM',
            friday: '6:00 AM - 11:00 PM',
            saturday: '7:00 AM - 11:00 PM',
            sunday: '8:00 AM - 9:00 PM'
        },
        services: ['fuel', 'shop'],
        amenities: ['Parking', 'Disabled Access'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded'],
        manager: 'David Power',
        established: 2017,
        is24Hours: false,
        hasCarWash: false,
        hasShop: true,
        hasCafe: false,
        hasATM: false,
    },
    {
        id: '6',
        name: 'Stargas Kilkenny Castle',
        address: '987 High Street',
        city: 'Kilkenny',
        county: 'Kilkenny',
        eircode: 'R95 MNO6',
        coordinates: { lat: 52.6541, lng: -7.2448 },
        phone: '+353 56 234 5678',
        email: 'kilkenny.castle@stargas.ie',
        openingHours: {
            monday: '7:00 AM - 9:00 PM',
            tuesday: '7:00 AM - 9:00 PM',
            wednesday: '7:00 AM - 9:00 PM',
            thursday: '7:00 AM - 9:00 PM',
            friday: '7:00 AM - 10:00 PM',
            saturday: '8:00 AM - 10:00 PM',
            sunday: '9:00 AM - 8:00 PM'
        },
        services: ['fuel', 'shop', 'coffee'],
        amenities: ['Free WiFi', 'Parking', 'Disabled Access', 'Toilets'],
        fuel_types: ['Petrol', 'Diesel', 'Premium Unleaded'],
        manager: 'Aoife Ryan',
        established: 2021,
        is24Hours: false,
        hasCarWash: false,
        hasShop: true,
        hasCafe: true,
        hasATM: false,
    },
];

// Service icons mapping
const serviceIcons = {
    fuel: { icon: 'fas fa-gas-pump', label: 'Fuel' },
    shop: { icon: 'fas fa-shopping-bag', label: 'Shop' },
    'car-wash': { icon: 'fas fa-car', label: 'Car Wash' },
    coffee: { icon: 'fas fa-coffee', label: 'Coffee' },
    atm: { icon: 'fas fa-credit-card', label: 'ATM' },
};

// Amenity icons mapping
const amenityIcons = {
    'Free WiFi': { icon: 'fas fa-wifi', label: 'Free WiFi' },
    'Parking': { icon: 'fas fa-parking', label: 'Parking' },
    'Disabled Access': { icon: 'fas fa-wheelchair', label: 'Disabled Access' },
    'Toilets': { icon: 'fas fa-restroom', label: 'Toilets' },
    'Electric Charging': { icon: 'fas fa-bolt', label: 'Electric Charging' },
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { storeData, serviceIcons, amenityIcons };
}